@extends('layouts.app')

@section('styles')

@endsection

@section('content')
<div class="mx-10">
    <h1 class="text-left text-gray-900 text-3xl">Epic Win Sporting Goods</h1>
    <h2 class="text-gray-800 text-2xl">- Terms Of Service</h2>
    <div class="mt-3 p-4 text-gray-700 text-lg">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu felis bibendum ut tristique. Neque ornare aenean euismod elementum nisi quis eleifend quam. Fames ac turpis egestas sed tempus urna et pharetra pharetra. In iaculis nunc sed augue lacus viverra vitae congue eu. Vitae suscipit tellus mauris a. Id venenatis a condimentum vitae sapien. Mauris in aliquam sem fringilla ut morbi tincidunt. Sagittis nisl rhoncus mattis rhoncus urna neque. Lacus luctus accumsan tortor posuere ac ut. Egestas integer eget aliquet nibh. Sed arcu non odio euismod lacinia. Placerat vestibulum lectus mauris ultrices eros in. Varius vel pharetra vel turpis nunc eget. Montes nascetur ridiculus mus mauris. Dictumst quisque sagittis purus sit amet volutpat. Arcu odio ut sem nulla. Viverra nibh cras pulvinar mattis. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Viverra nibh cras pulvinar mattis nunc sed blandit libero.
            <br class="mb-5">
            Egestas integer eget aliquet nibh. In aliquam sem fringilla ut morbi. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Amet nisl suscipit adipiscing bibendum est. Ut morbi tincidunt augue interdum. Sit amet massa vitae tortor condimentum lacinia. Mattis vulputate enim nulla aliquet. Lacus vestibulum sed arcu non odio euismod lacinia at. Id leo in vitae turpis massa. Ultrices vitae auctor eu augue. Aenean pharetra magna ac placerat vestibulum. Tellus orci ac auctor augue. Leo duis ut diam quam nulla porttitor massa id. Et magnis dis parturient montes nascetur ridiculus. Turpis egestas sed tempus urna et pharetra. Urna neque viverra justo nec ultrices.
            <br class="mb-5">
            Malesuada fames ac turpis egestas. Aenean et tortor at risus viverra. Facilisis leo vel fringilla est. Eget gravida cum sociis natoque. Nunc sed velit dignissim sodales ut. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Quam elementum pulvinar etiam non quam lacus suspendisse. Volutpat odio facilisis mauris sit amet. Scelerisque in dictum non consectetur a. Adipiscing commodo elit at imperdiet. Rhoncus mattis rhoncus urna neque viverra justo nec. Sed velit dignissim sodales ut eu sem integer vitae justo. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Est sit amet facilisis magna etiam.
            <br class="mb-5">
            Suspendisse in est ante in nibh mauris cursus. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Donec ultrices tincidunt arcu non sodales. Scelerisque viverra mauris in aliquam sem. Enim sed faucibus turpis in eu mi bibendum neque egestas. Cras adipiscing enim eu turpis egestas pretium. Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Imperdiet sed euismod nisi porta lorem mollis. Ultricies mi eget mauris pharetra. Vitae aliquet nec ullamcorper sit amet. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Duis ut diam quam nulla porttitor massa id neque aliquam. Ac placerat vestibulum lectus mauris ultrices eros in. Tortor id aliquet lectus proin nibh nisl. Diam volutpat commodo sed egestas. Diam phasellus vestibulum lorem sed. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Id donec ultrices tincidunt arcu non sodales. Lectus nulla at volutpat diam ut venenatis tellus in metus.
            <br class="mb-5">
            At elementum eu facilisis sed odio morbi. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Quis risus sed vulputate odio. Mollis aliquam ut porttitor leo a diam sollicitudin. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Arcu cursus euismod quis viverra nibh cras. Iaculis nunc sed augue lacus viverra vitae congue. Metus aliquam eleifend mi in. Et netus et malesuada fames ac turpis egestas. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. In hendrerit gravida rutrum quisque non tellus orci ac auctor. At ultrices mi tempus imperdiet nulla malesuada. Vel facilisis volutpat est velit egestas dui id ornare. Volutpat sed cras ornare arcu dui vivamus arcu felis. Montes nascetur ridiculus mus mauris vitae ultricies leo. Eget duis at tellus at urna condimentum mattis pellentesque id. Augue lacus viverra vitae congue eu consequat ac felis donec.
            <br class="mb-5">
            Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Id leo in vitae turpis massa sed elementum. Venenatis cras sed felis eget velit aliquet sagittis id. Mattis pellentesque id nibh tortor id aliquet. Nullam ac tortor vitae purus faucibus ornare. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Quam quisque id diam vel quam elementum pulvinar etiam. Consectetur purus ut faucibus pulvinar elementum integer. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Imperdiet massa tincidunt nunc pulvinar sapien et. Accumsan sit amet nulla facilisi. Consequat id porta nibh venenatis cras sed felis. Sodales ut etiam sit amet nisl. Neque vitae tempus quam pellentesque nec nam. Posuere urna nec tincidunt praesent semper feugiat.
            <br class="mb-5">
            Tellus in hac habitasse platea dictumst vestibulum. Fusce id velit ut tortor. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Aliquet eget sit amet tellus cras adipiscing enim eu. Quis ipsum suspendisse ultrices gravida dictum fusce ut. Diam phasellus vestibulum lorem sed risus. Morbi tristique senectus et netus et malesuada. Ut faucibus pulvinar elementum integer enim neque. Porttitor lacus luctus accumsan tortor posuere ac. Metus dictum at tempor commodo ullamcorper. Tortor dignissim convallis aenean et tortor at risus viverra. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Nunc sed velit dignissim sodales ut eu. Quis ipsum suspendisse ultrices gravida dictum fusce. Amet luctus venenatis lectus magna. Quis auctor elit sed vulputate mi sit amet mauris. Et egestas quis ipsum suspendisse ultrices gravida dictum. Integer quis auctor elit sed vulputate.
            <br class="mb-5">
            Tincidunt vitae semper quis lectus nulla at volutpat diam. At lectus urna duis convallis convallis tellus id interdum. Enim sit amet venenatis urna cursus eget. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Ultrices tincidunt arcu non sodales neque sodales ut. Est placerat in egestas erat. Diam sollicitudin tempor id eu nisl nunc. Eu scelerisque felis imperdiet proin fermentum. Vitae ultricies leo integer malesuada nunc vel. Gravida quis blandit turpis cursus. Odio ut enim blandit volutpat maecenas volutpat. Diam ut venenatis tellus in metus vulputate eu scelerisque felis.
            <br class="mb-5">
            Donec enim diam vulputate ut pharetra. Ut etiam sit amet nisl. Etiam erat velit scelerisque in dictum non consectetur a. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Elementum pulvinar etiam non quam lacus suspendisse. Dui accumsan sit amet nulla facilisi morbi. Vitae suscipit tellus mauris a diam maecenas. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Ac orci phasellus egestas tellus rutrum. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Cursus sit amet dictum sit amet justo. Leo urna molestie at elementum eu facilisis sed odio. Commodo elit at imperdiet dui accumsan. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl.
            <br class="mb-5">
            Montes nascetur ridiculus mus mauris. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Nulla at volutpat diam ut venenatis. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Mattis nunc sed blandit libero volutpat sed cras ornare. Maecenas sed enim ut sem viverra aliquet eget. Pretium viverra suspendisse potenti nullam. Gravida quis blandit turpis cursus in hac habitasse. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. A diam sollicitudin tempor id eu nisl nunc. Magna etiam tempor orci eu lobortis elementum nibh. In iaculis nunc sed augue lacus viverra vitae. Elit pellentesque habitant morbi tristique senectus. Lectus nulla at volutpat diam. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.
        </p>
    </div>
</div>
@endsection

@section('scripts')

@endsection
